### ISSUE TITLE
Add example application for music player to /docs

### ISSUE THREAD

**Issue by santolucito** [Barnard-PL-Labs/tsltools#11]
Anything in the `docs/` directory is live at https://barnard-pl-labs.github.io/tsltools/. Let's put thee blog post write up here (and maybe a more verbose/narrative version can go on medium/notion/your personal page/etc)

**Comment by Rheakk** [comment]
Danielle and I wrote up a blog post summarizing what we have covered so far - we included a general explanation of TSL and dove into the 4 TSL specifications we discussed so far. I worked on the general explanation of TSL, and Danielle explained each of the examples. We included screenshots of the code to supplement our explanations.

**Comment by dc3347** [comment]
Updates: Rhea and I worked on the blog post this week. We split up the work, so I worked on explaining some examples of TSL specifications and Rhea worked on an in-depth summary of TSL and its syntax.

**Comment by santolucito** [comment]
do you have a link to a draft of the blog post? Or can you push what you have (assuming you are using markdown or some type of plaintext) to this repo in the docs folder?

**Comment by Rheakk** [comment]
I think we did add it to the docs repo, is it there for you?

Best,
Rhea

**Comment by santolucito** [comment]
Ah I see! You can reference commits in an issue by pasting the hash (like so: 8842a08ea19e685dd84865a337194a20d6507b02), or by including the commit number (in this case, #11) in the commit message from the command line.

**Comment by Rheakk** [comment]
Oh got it, will do that next time - thanks for the tip! Glad it’s there in
the repo.

**Comment by dc3347** [comment]
Update 3/1/22: I edited the blog post to include side by side examples of the tsl specification and code and cleaned up the intro section. Rhea and I also were able to create a play/pause button using html and sonify the 2 notes using tonejs. Here is the code: [2a07afd](https://github.com/Barnard-PL-Labs/tsltools/commit/2a07afd0f4012702e28d321b4687aba15706331e)

**Comment by Rheakk** [comment]
Update 3/1/22: Made edits to emphasize the semantic significance of TSL rather than the editing ease. Added in link to the paper and proper citation. Made small suggested edits as well. Worked on sonifying two notes with Danielle using tone.js, managed to create a play/pause button that plays these alternating notes. Code commit: [2a07afd](https://github.com/Barnard-PL-Labs/tsltools/commit/2a07afd0f4012702e28d321b4687aba15706331e)
