### ISSUE TITLE
Pipeline to sonify output with JS

### ISSUE THREAD

**Issue by dc3347** [Barnard-PL-Labs/tsltools#19]
Right now we manually convert code generated from the TSL spec to JS code in order to use ToneJS to sonify it. Instead, we should directly output the JS code from the TSL spec.

To do this, we need to write a JS rendering module. This will be done via replicating and modifying Python.hs. The goal is to put in a TSL spec and get out JS code that plays music.

**Comment by dc3347** [comment]
Update 3/28/2022:
This week we added links to the examples in the blog post: [c631c04](https://github.com/Barnard-PL-Labs/tsltools/commit/c631c049db3fe7fc064b1c84f69a7cfe40fb1903)
We also created a template for generating js from the tsl spec and began working on modifying it: [b6d8247](https://github.com/Barnard-PL-Labs/tsltools/commit/b6d8247b9ec7bb9cabcd8b12a7df6e28ac449a20)

Currently, we are working on the following modifications to the template code in the above file:

1. Replace the colon that indicates the beginning of a code block by {
2. Add } at the end of a code block
3. Surround conditions in if and while statements by parentheses
4. Add semi-colons at the end of each statement
5. Replace keyword not with the symbol !
6. Replace keyword and by symbols &&
7. Replace keyword or by symbols ||
8. Replace keyword True and False by true and false
9. Replace keyword elif by else if

**Comment by Rheakk** [comment]
Update (3/28/22): We added links to our blogpost that will go to the music player webpage (see commit in Danielle's update). We began creating a JavaScript pipeline to convert from TSL to generated code by going through each relevant file and adding any accommodations for JavaScript (see Danielle's update as well). Most files already have JavaScript included, since there is already a flag created for generating JavaScript code for TSL synthesis. Our next steps are to further modify JavaScript.hs to get the synthesis working.

**Comment by dc3347** [comment]
Update (4/5/22): This week Rhea and I split up the work. I did the following tasks:

1. I changed the variable names in our tsl spec for 1 and 2 notes to work with ToneJS: [f690045](https://github.com/Barnard-PL-Labs/tsltools/commit/f690045a2f6143b1b02ff83be3bd0a41e22b04be)
2. I debugged the javascript tonejs code from the last meeting. This was where we were having issues sonifying the generated js code (it was only playing 1 note instead of 2) after copying and pasting into an online ide. The solution is we need to change the `if` to an `else if` (will require help from Mark to do this using tslsynth).
3. Lastly, I worked with haskell higher order functions to try to add a semicolon in the Javascript.hs file: [b1765e3](https://github.com/Barnard-PL-Labs/tsltools/commit/b1765e31499a74749e4f4ef0fb501c47940a41b7) and [6d5c563](https://github.com/Barnard-PL-Labs/tsltools/commit/6d5c56324dbeb499f9751afe0a8a5a3a6928b6db). Below is a sample output of the `replaceUpdate` function.  <img width="952" alt="Screen Shot 2022-04-04 at 10 24 28 PM" src="https://user-images.githubusercontent.com/55637930/161666740-70d81a90-37a4-4956-bbdc-e7a89cb183ce.png">
However, I am having trouble incorporating this into the existing code and keep getting the following errors:
<img width="617" alt="Screen Shot 2022-04-04 at 10 26 11 PM" src="https://user-images.githubusercontent.com/55637930/161666896-01aa65c6-141a-4452-b121-f9c47e9a3d99.png">

**Comment by Rheakk** [comment]
Update (4/5/22): This week I wrote a bash script that dumps the tonejs javascript code into the file with the generated code from tsl synthesis. We can incorporate this script by having the tonejs code in its own file, and passing in filenames for the generated code files from tsl synthesis as arguments to the bash script. Next steps would be to incorporate this bash script into a larger script that runs both the synthesis and adds in the tonejs code ([881e7d8](https://github.com/Barnard-PL-Labs/tsltools/commit/881e7d8f94b3a91020dcb8492197a9455c850b94)).

**Comment by dc3347** [comment]
The next goal is to create a website to put in a TSL spec and get out JS code that plays music. Will create a new issue for this
