### ISSUE TITLE
Website for TSL to JS synthesis

### ISSUE THREAD

**Issue by dc3347** [Barnard-PL-Labs/tsltools#20]
We plan to use Flask and python to write web app which will provide the user the ability to put in a TSL spec, click a button, and have the generated JavaScript code be outputted directly onto the webpage.

**Comment by dc3347** [comment]
Update 4/11/2022: This week I did the following:

- Updated example code on blog to be in javascript: [b965745](https://github.com/Barnard-PL-Labs/tsltools/commit/b96574503429d389a10ab3630a6797f7a22ec52a)
- Added semicolon to JavaScript.hs: [bf3bb45](https://github.com/Barnard-PL-Labs/tsltools/commit/bf3bb4553b6925bb6463171f89ee6a439a829c32)
- Semi-fixed the bug by changing `state` to `nextState` in the conditionals and then setting `state = nextState` at the end. There is a small issue with the latter where the statement appears after each conditional. I need help with this: [9fc2c09](https://github.com/Barnard-PL-Labs/tsltools/commit/9fc2c09afca28e9305a62c409c0b7a43c5a9d51a). Here is a screenshot:
<img width="274" alt="Screen Shot 2022-04-11 at 9 39 25 PM" src="https://user-images.githubusercontent.com/55637930/162861604-d4fae589-6222-422b-9f08-24d53e19e29d.png">
- Created flow diagram for frontend and backend of our website; we are using Flask in python to do this:
<img width="751" alt="Front-end" src="https://user-images.githubusercontent.com/55637930/162861633-82e643da-f033-4dc4-9aa6-119df4ebd20f.png">
- Created Note.sh that runs the tslsynthesizer and pipes the output to a text file called Note.txt. Then, the text file with the js code is displayed on the web app. To run the app, cd into the flask_app directory and type python3 app.py.  [e3a3380](https://github.com/Barnard-PL-Labs/tsltools/commit/e3a3380c075ae515c90ccc541b40471cb998a43e)


Anything we need from Mark:
- Help with fixing the `state = nextState`
- Not sure about the backend for the website; currently web app needs to run locally to work

Other TODOs:
- need to make G4 and E4 into strings in the generated js code 
- add to blog post (final paper)

**Comment by santolucito** [comment]
https://barnard-pl-labs.github.io/tsl-api/
