### ISSUE TITLE
Sonification of 3 note examples

### ISSUE THREAD

**Issue by dc3347** [Barnard-PL-Labs/tsltools#21]
We will write TSL for various examples of 3 note (G, C, and E) combinations and sonify them.

**Comment by dc3347** [comment]
4/19/22 Update: 

This week I created two examples for sonifying 3 notes while Rhea created two other examples. This involved writing the TSL specification ([15809b1](https://github.com/Barnard-PL-Labs/tsltools/commit/15809b16e45931e7b1f2449b91b4f2797a0affef) and [04a83bd](https://github.com/Barnard-PL-Labs/tsltools/commit/04a83bd3a4512e7e08f00768f050eab6a429ebde)), sonifying it in tonejs ([f566af1](https://github.com/Barnard-PL-Labs/tsltools/commit/f566af1006290fda7c15c18b9549bc82eeef1072)), and updating the blog post by including a writeup and adding links for the button to play examples 5 an 6 ([457c008](https://github.com/Barnard-PL-Labs/tsltools/commit/457c0088d8f9b4d7fc89949aef8990280326a610) and [d5f0e5d](https://github.com/Barnard-PL-Labs/tsltools/commit/d5f0e5d84062b7b12227cd2aec249cde2f5a9a7a)). The next steps are to work with Rhea to generate varying rhythms for 2 and 3 notes, as well as fixing the issues that we're running into.

Current issues that need to be fixed are:
1. In the generated js code, we only need to have `state == newState` appear once at the end. This needs to be fixed in the haskell code but we need help. 
2. Convert the note variable names such as `G4` to strings such as `"G4"` in the js code
3. Initialize `state` and `noteToPlay` variables in the tonejs code
4. In Rhea's script, we need to put the generated js logic into the `updateStateMachine()` function instead of just concatenating the two files.

**Comment by Rheakk** [comment]
4/19/22 Update: I added two more TSL specifications for musical sequences, one that plays the pattern C E G repeatedly, and the other I attempted the pattern E G D G E G D G E... however I was having trouble creating the spec for this. I also need to handle some git issues so I was not able to add in my commits yet. Once I figure this out, I will add my changes to the blogpost.

**Comment by dc3347** [comment]
Done
