### ISSUE TITLE
clean up tslsynth file management

### ISSUE THREAD

**Issue by santolucito** [Barnard-PL-Labs/tsltools#35]
sometimes uses test and sometimes tmp for intermediate files. really shouldn't be generating intermediate files at all (at least by default). 

https://github.com/Barnard-PL-Labs/tsltools/blob/699709bc78d5cbb206a1644f52cf34520b917595/src/tools/tslsynth/Main.hs#L55

**Comment by leoqiao18** [comment]
Should we add flags to still provide the option to see these intermediate files?

**Comment by santolucito** [comment]
yes for sure, they are quite helpful - just should be put in a sensible
place and named better than we currently have

**Comment by leoqiao18** [comment]
Implemented in #60
