### ISSUE TITLE
tslmt2tsl vs tslpreprocess

### ISSUE THREAD

**Issue by santolucito** [Barnard-PL-Labs/tsltools#36]
dont these do the same thing?

**Comment by wonhyukchoi** [comment]
`tslmt2tsl` adds SyGuS assumption to a TSL-MT specificationto transform it into a TSL specification.
`tslpreprocess` transforms a sugared TSL specification (with number literals and binary operators) and transforms it into the vanilla TSL

**Comment by santolucito** [comment]
makes sense!
